all: main.o

main.o: main.cpp
	g++ -I/opt/homebrew/Cellar/sdl2/2.0.22/include -I/opt/homebrew/Cellar/sdl2/2.0.22/include/SDL2 -I/opt/homebrew/Cellar/sdl2_ttf/2.20.0/include -L/opt/homebrew/lib -lSDL2 -lSDL2_ttf main.cpp -o obj/main.o
